# frozen_string_literal: true

namespace :rbi do
  desc 'generate fixture rbi files'
  task fixtures: :environment do
    require 'active_record/fixtures'
    require 'parlour'

    fixtures_dir = ActiveRecord::Tasks::DatabaseTasks.fixtures_path
    fixture_sets =
      ActiveRecord::FixtureSet.create_fixtures(
        fixtures_dir,
        Dir["#{fixtures_dir}/**/*.yml"].map do |filepath|
          filepath[(fixtures_dir.size + 1)..-5]
        end
      )

    parlour = T.let(Parlour::RbiGenerator.new, Parlour::RbiGenerator)
    parlour.root.add_comments([
      'This is an autogenerated file for Rails test fixtures.',
      'Please rerun bundle exec rake rbi:fixtures to regenerate.'
    ])

    parlour.root.create_class('ActiveSupport::TestCase') do |rbi|
      fixture_sets.each do |fixture_set|  
        rbi.create_method(
          fixture_set.name,
          parameters: [
            Parlour::RbiGenerator::Parameter.new('fixture_name', type: 'Symbol')
          ],
          return_type: fixture_set.model_class.name,
          class_method: false,
        )
      end
    end

    File.write(Rails.root.join('sorbet', 'fixtures.rbi'), parlour.rbi)
  end
end
